import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { CustomerLayout, useCustomerAuth } from '@/components/customer/customer-layout';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { useToast } from '@/hooks/use-toast';
import { queryClient } from '@/lib/queryClient';
import { isAutoGeneratedSerial } from '@/lib/utils';
import { Package, Upload, Clock, CheckCircle, Search, ChevronLeft, ChevronRight, Smartphone, Laptop, FileText } from 'lucide-react';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';

interface CustomerOrder {
  id: number;
  voucherCode: string;
  name: string;
  contact: string;
  deviceType: string;
  serialNumber: string;
  brand: string;
  modelName: string;
  invoiceValue: number;
  dateOfPurchase: string;
  registrationDate: string;
  isVerified: boolean;
  invoiceFile?: string;
  planName?: string;
  claimStatus?: string;
  registrationSource?: string;
}

export default function CustomerOrdersPage() {
  const { customerPhone, isAuthenticated } = useCustomerAuth();
  const { toast } = useToast();
  const [searchTerm, setSearchTerm] = useState('');
  const [currentPage, setCurrentPage] = useState(1);
  const [uploadingInvoice, setUploadingInvoice] = useState<number | null>(null);
  const [filters, setFilters] = useState({
    source: 'all',
    status: 'all',
    registration: 'all'
  });
  const [sortBy, setSortBy] = useState({ field: 'dateOfPurchase', direction: 'desc' });
  const itemsPerPage = 10;

  const { data: orders = [], isLoading } = useQuery<CustomerOrder[]>({
    queryKey: ['/api/customer/orders', customerPhone],
    queryFn: async () => {
      const response = await fetch(`/api/customer/orders?phone=${customerPhone}`);
      if (!response.ok) throw new Error('Failed to fetch orders');
      return response.json();
    },
    enabled: isAuthenticated && !!customerPhone
  });

  const filteredOrders = orders.filter(order => {
    const searchMatch = 
      order.voucherCode.toLowerCase().includes(searchTerm.toLowerCase()) ||
      order.brand.toLowerCase().includes(searchTerm.toLowerCase()) ||
      order.modelName.toLowerCase().includes(searchTerm.toLowerCase()) ||
      order.serialNumber.toLowerCase().includes(searchTerm.toLowerCase()) ||
      order.dateOfPurchase.includes(searchTerm);

    const sourceMatch = filters.source === 'all' || 
      (order.registrationSource?.toLowerCase() || 'website') === filters.source.toLowerCase();
    
    const statusMatch = filters.status === 'all' || (() => {
      const status = order.claimStatus || (order.isVerified ? 'verified' : 'pending');
      return status.toLowerCase() === filters.status.toLowerCase();
    })();

    const registrationMatch = filters.registration === 'all' || (() => {
      const isRegistered = !isAutoGeneratedSerial(order.serialNumber);
      return filters.registration === 'registered' ? isRegistered : !isRegistered;
    })();

    return searchMatch && sourceMatch && statusMatch && registrationMatch;
  }).sort((a, b) => {
    const aValue = a[sortBy.field as keyof CustomerOrder] || '';
    const bValue = b[sortBy.field as keyof CustomerOrder] || '';
    
    if (sortBy.direction === 'asc') {
      return String(aValue).localeCompare(String(bValue));
    } else {
      return String(bValue).localeCompare(String(aValue));
    }
  });

  const totalPages = Math.ceil(filteredOrders.length / itemsPerPage);
  const paginatedOrders = filteredOrders.slice((currentPage - 1) * itemsPerPage, currentPage * itemsPerPage);

  const handleInvoiceUpload = async (orderId: number, file: File) => {
    setUploadingInvoice(orderId);
    const formData = new FormData();
    formData.append('invoice', file);
    formData.append('orderId', orderId.toString());
    formData.append('phone', customerPhone);

    try {
      const response = await fetch('/api/customer/upload-invoice', {
        method: 'POST',
        body: formData
      });
      if (!response.ok) throw new Error('Failed to upload invoice');
      queryClient.invalidateQueries({ queryKey: ['/api/customer/orders', customerPhone] });
      toast({ title: "Success", description: "Invoice uploaded successfully" });
    } catch (error: any) {
      toast({ title: "Error", description: error.message, variant: "destructive" });
    } finally {
      setUploadingInvoice(null);
    }
  };

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-IN', {
      day: '2-digit', month: 'short', year: 'numeric'
    });
  };

  const isInvoiceMissing = (invoiceFile: string | undefined) => {
    return !invoiceFile || invoiceFile === 'N/A' || invoiceFile.trim() === '';
  };

  const getStatusBadge = (order: CustomerOrder) => {
    if (order.claimStatus === 'approved' || order.claimStatus === 'paid') {
      return <Badge className="bg-purple-100 text-purple-700">Claimed</Badge>;
    }
    if (order.claimStatus === 'pending' || order.claimStatus === 'processing') {
      return <Badge className="bg-orange-100 text-orange-700">Claim Processing</Badge>;
    }
    if (order.isVerified) {
      return <Badge className="bg-green-100 text-green-700">Verified</Badge>;
    }
    return <Badge className="bg-yellow-100 text-yellow-700">Pending</Badge>;
  };

  return (
    <CustomerLayout title="My Orders" description="View and manage your protected devices">
      <Card className="rounded-xl border-gray-100">
        <CardContent className="p-0">
          <div className="p-4 border-b border-gray-100 space-y-4">
            <div className="flex flex-col sm:flex-row gap-3 justify-between">
              <div className="relative flex-1 max-w-sm">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-400" />
                <Input
                  placeholder="Search IMEI, Voucher, Brand..."
                  value={searchTerm}
                  onChange={(e) => { setSearchTerm(e.target.value); setCurrentPage(1); }}
                  className="pl-10 rounded-lg border-gray-200"
                />
              </div>
              <div className="text-sm text-gray-500 self-center">
                Showing {paginatedOrders.length} of {filteredOrders.length} orders
              </div>
            </div>
            
            <div className="flex flex-wrap gap-2">
              <Select value={filters.source} onValueChange={(v) => setFilters(f => ({...f, source: v}))}>
                <SelectTrigger className="w-[130px] h-9 text-xs rounded-lg">
                  <SelectValue placeholder="Source" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Sources</SelectItem>
                  <SelectItem value="website">Website</SelectItem>
                  <SelectItem value="acer">Acer</SelectItem>
                  <SelectItem value="amazon">Amazon</SelectItem>
                </SelectContent>
              </Select>

              <Select value={filters.status} onValueChange={(v) => setFilters(f => ({...f, status: v}))}>
                <SelectTrigger className="w-[130px] h-9 text-xs rounded-lg">
                  <SelectValue placeholder="Status" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Status</SelectItem>
                  <SelectItem value="verified">Verified</SelectItem>
                  <SelectItem value="pending">Pending</SelectItem>
                  <SelectItem value="claimed">Claimed</SelectItem>
                </SelectContent>
              </Select>

              <Select value={filters.registration} onValueChange={(v) => setFilters(f => ({...f, registration: v}))}>
                <SelectTrigger className="w-[130px] h-9 text-xs rounded-lg">
                  <SelectValue placeholder="Registration" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Registration</SelectItem>
                  <SelectItem value="registered">Registered</SelectItem>
                  <SelectItem value="unregistered">Unregistered</SelectItem>
                </SelectContent>
              </Select>

              <Select value={`${sortBy.field}-${sortBy.direction}`} onValueChange={(v) => {
                const [field, direction] = v.split('-');
                setSortBy({ field, direction: direction as 'asc' | 'desc' });
              }}>
                <SelectTrigger className="w-[160px] h-9 text-xs rounded-lg">
                  <SelectValue placeholder="Sort By" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="dateOfPurchase-desc">Latest Purchase</SelectItem>
                  <SelectItem value="dateOfPurchase-asc">Oldest Purchase</SelectItem>
                  <SelectItem value="invoiceValue-desc">Highest Value</SelectItem>
                  <SelectItem value="invoiceValue-asc">Lowest Value</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          {isLoading ? (
            <div className="p-8 text-center">
              <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-[#254696] mx-auto"></div>
            </div>
          ) : orders.length === 0 ? (
            <div className="p-12 text-center">
              <Package className="h-12 w-12 text-gray-300 mx-auto mb-4" />
              <h3 className="text-lg font-bold text-gray-900 mb-2">No Orders Yet</h3>
              <p className="text-gray-500 mb-4">You haven't purchased any BBG protection plans yet.</p>
              <Button onClick={() => window.location.href = '/'} className="bg-[#254696]">
                Get Protected
              </Button>
            </div>
          ) : (
            <>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
                {paginatedOrders.map((order) => {
                  const DeviceIcon = order.deviceType?.toLowerCase() === 'laptop' ? Laptop : Smartphone;
                  const needsInvoice = isInvoiceMissing(order.invoiceFile);
                  
                  // Format registration source for display
                  const sourceDisplay = order.registrationSource 
                    ? order.registrationSource.charAt(0).toUpperCase() + order.registrationSource.slice(1).toLowerCase()
                    : 'Website';

                  return (
                    <Card key={order.id} className={`overflow-hidden border transition-all hover:shadow-sm ${needsInvoice ? 'bg-orange-50/40 border-orange-200' : 'bg-white border-gray-200'} rounded-lg`}>
                      <div className="p-3 space-y-3">
                        {/* Header: Device Info */}
                        <div className="flex items-center gap-3">
                          <div className={`w-8 h-8 rounded-md flex items-center justify-center shrink-0 ${needsInvoice ? 'bg-orange-100 text-orange-600' : 'bg-gray-100 text-gray-600'}`}>
                            <DeviceIcon className="h-4 w-4" />
                          </div>
                          <div className="min-w-0 flex-1">
                            <h4 className="font-semibold text-gray-900 text-sm truncate">{order.brand} {order.modelName}</h4>
                            <p className="text-xs text-gray-500 font-mono truncate">
                              {isAutoGeneratedSerial(order.serialNumber) ? "Serial Pending" : order.serialNumber}
                            </p>
                          </div>
                          {getStatusBadge(order)}
                        </div>

                        {/* Details Grid */}
                        <div className="grid grid-cols-2 gap-2 text-xs bg-gray-50/50 p-2 rounded-md">
                          <div>
                            <p className="text-gray-400 mb-0.5">Voucher</p>
                            <p className="font-medium text-gray-700 font-mono">{order.voucherCode}</p>
                          </div>
                          <div className="text-right">
                            <p className="text-gray-400 mb-0.5">Value</p>
                            <p className="font-medium text-gray-900">₹{order.invoiceValue?.toLocaleString()}</p>
                          </div>
                          <div>
                            <p className="text-gray-400 mb-0.5">Date</p>
                            <p className="font-medium text-gray-700">{formatDate(order.dateOfPurchase)}</p>
                          </div>
                          <div className="text-right">
                            <p className="text-gray-400 mb-0.5">Source</p>
                            <p className="font-medium text-gray-700">{sourceDisplay}</p>
                          </div>
                        </div>

                        {/* Actions Footer */}
                        <div className="flex items-center justify-end gap-2 pt-1">
                          {needsInvoice && (
                            <div className="relative">
                              <input
                                type="file"
                                accept=".pdf,.jpg,.jpeg,.png"
                                className="absolute inset-0 w-full h-full opacity-0 cursor-pointer z-10"
                                onChange={(e) => {
                                  const file = e.target.files?.[0];
                                  if (file) handleInvoiceUpload(order.id, file);
                                }}
                                disabled={uploadingInvoice === order.id}
                              />
                              <Button 
                                variant="outline" 
                                size="sm" 
                                className="h-7 text-xs border-orange-200 text-orange-700 hover:bg-orange-50 hover:text-orange-800"
                                disabled={uploadingInvoice === order.id}
                              >
                                {uploadingInvoice === order.id ? (
                                  <Clock className="h-3 w-3 mr-1.5 animate-spin" />
                                ) : (
                                  <Upload className="h-3 w-3 mr-1.5" />
                                )}
                                Upload Invoice
                              </Button>
                            </div>
                          )}
                          
                          {(isAutoGeneratedSerial(order.serialNumber) || !order.serialNumber) ? (
                            <Button 
                              variant="outline" 
                               size="sm"
                              className="h-7 text-xs border-[#254696] text-[#254696] hover:bg-[#254696] hover:text-white"
                              onClick={() => window.location.href = '/register'}
                            >
                              <CheckCircle className="h-3 w-3 mr-1.5" />
                              Register
                            </Button>
                          ) : (
                            !order.claimStatus && order.isVerified && !needsInvoice && (
                              <Button 
                                variant="default" 
                                size="sm"
                                className="h-7 text-xs bg-[#254696] hover:bg-[#1a3375]"
                                onClick={async () => {
                                  try {
                                    const response = await fetch('/api/claims/check', {
                                      method: 'POST',
                                      headers: { 'Content-Type': 'application/json' },
                                      body: JSON.stringify({ voucherCode: order.voucherCode })
                                    });
                                    if (response.ok) {
                                      window.location.href = `/customer/claims?voucher=${order.voucherCode}`;
                                    } else {
                                      const data = await response.json();
                                      toast({ title: "Not Eligible", description: data.message || "You are not eligible for a claim yet.", variant: "destructive" });
                                    }
                                  } catch (error) {
                                    toast({ title: "Error", description: "Failed to check eligibility", variant: "destructive" });
                                  }
                                }}
                              >
                                <FileText className="h-3 w-3 mr-1.5" />
                                Claim
                              </Button>
                            )
                          )}
                          
                          {/* Fallback/Generic Action if needed or just empty space usage */}
                          {!needsInvoice && !(!order.claimStatus && order.isVerified) && !isAutoGeneratedSerial(order.serialNumber) && (
                             <Button variant="ghost" size="sm" className="h-7 text-xs text-gray-400 cursor-default hover:bg-transparent">
                               No Actions
                             </Button>
                          )}
                        </div>
                      </div>
                    </Card>
                  );
                })}
              </div>

              {totalPages > 1 && (
                <div className="mt-6 flex items-center justify-between">
                  <p className="text-sm text-gray-500">
                    Page {currentPage} of {totalPages}
                  </p>
                  <div className="flex items-center gap-2">
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => setCurrentPage(p => Math.max(1, p - 1))}
                      disabled={currentPage === 1}
                    >
                      <ChevronLeft className="h-4 w-4" />
                    </Button>
                    {Array.from({ length: Math.min(5, totalPages) }, (_, i) => {
                      let pageNum;
                      if (totalPages <= 5) {
                        pageNum = i + 1;
                      } else if (currentPage <= 3) {
                        pageNum = i + 1;
                      } else if (currentPage >= totalPages - 2) {
                        pageNum = totalPages - 4 + i;
                      } else {
                        pageNum = currentPage - 2 + i;
                      }
                      return (
                        <Button
                          key={pageNum}
                          variant={currentPage === pageNum ? "default" : "outline"}
                          size="sm"
                          onClick={() => setCurrentPage(pageNum)}
                          className={currentPage === pageNum ? 'bg-[#254696]' : ''}
                        >
                          {pageNum}
                        </Button>
                      );
                    })}
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => setCurrentPage(p => Math.min(totalPages, p + 1))}
                      disabled={currentPage === totalPages}
                    >
                      <ChevronRight className="h-4 w-4" />
                    </Button>
                  </div>
                </div>
              )}
            </>
          )}
        </CardContent>
      </Card>
    </CustomerLayout>
  );
}
